security:
    encoders:
        AppBundle\Entity\Usuarios:
            { algorithm: sha1, iterations: 1, encode_as_base64: false }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        usuarios:
           entity: { class: AppBundle\Entity\Usuarios }

    firewalls:
       frontend:
           pattern: ^/*
           security: true
           anonymous: ~
           form-login:
               login_path: login
               check_path: login_check
               default_target_path: lista_repostajes
           logout:
               path: logout
               target: home

    access_control:
       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/*, roles: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SUPER_ADMIN  ] }